/* citizenship-data.js — US Citizenship (USCIS naturalization civics test, 2008 version) study questions.
   Source of truth: official USCIS 100 Civics Questions & Answers. Volatile "current office-holder" and
   per-state items (President/VP/Speaker name, your Senators/Governor/capital) are intentionally omitted —
   those change over time and the real (oral) test accepts current/your-state answers. The stable,
   nationally-fixed facts become multiple-choice study questions here, in 5 languages.

   Shape (consumed by /citizenship/index.html):
     window.CIV = {
       ui:   { en:{...}, es,ru,tr,hi },                 // app UI strings
       cats: [ {id, kind, icon, name:{5lang}, blurb:{5lang}} ],
       q:    [ {cat, a, q:{5lang}, o:[ {5lang} x4 ], e:{5lang} } ]   // a = index of correct option (EN order)
     }
   Practice tests draw from the pool; the Learn lesson shows them all. Options keep EN order across langs. */
(function(){
  // compact per-question helper: L(en,es,ru,tr,hi)
  function L(en,es,ru,tr,hi){ return {en:en,es:es,ru:ru,tr:tr,hi:hi}; }

  var Q = [
  // ---- American Government: Principles ----
  { cat:"gov", a:0,
    q:L("What is the supreme law of the land?","¿Cuál es la ley suprema del país?","Какой высший закон страны?","Ülkenin en yüce yasası nedir?","देश का सर्वोच्च कानून क्या है?"),
    o:[L("The Constitution","La Constitución","Конституция","Anayasa","संविधान"),
       L("The Bill of Rights","La Carta de Derechos","Билль о правах","Haklar Bildirgesi","अधिकार विधेयक"),
       L("The Declaration of Independence","La Declaración de Independencia","Декларация независимости","Bağımsızlık Bildirgesi","स्वतंत्रता की घोषणा"),
       L("Federal law","La ley federal","Федеральный закон","Federal yasa","संघीय कानून")],
    e:L("The Constitution is the supreme law of the land.","La Constitución es la ley suprema del país.","Конституция — высший закон страны.","Anayasa ülkenin en yüce yasasıdır.","संविधान देश का सर्वोच्च कानून है।") },

  { cat:"gov", a:1,
    q:L("What does the Constitution do?","¿Qué hace la Constitución?","Что делает Конституция?","Anayasa ne yapar?","संविधान क्या करता है?"),
    o:[L("Declares war on other nations","Declara la guerra a otras naciones","Объявляет войну другим странам","Diğer uluslara savaş ilan eder","अन्य देशों पर युद्ध की घोषणा करता है"),
       L("Sets up the government and protects basic rights","Establece el gobierno y protege los derechos básicos","Создаёт правительство и защищает основные права","Hükümeti kurar ve temel hakları korur","सरकार स्थापित करता है और बुनियादी अधिकारों की रक्षा करता है"),
       L("Sets tax rates each year","Fija las tasas de impuestos cada año","Устанавливает налоговые ставки ежегодно","Her yıl vergi oranlarını belirler","हर साल कर दरें तय करता है"),
       L("Elects the President","Elige al Presidente","Избирает президента","Başkanı seçer","राष्ट्रपति चुनता है")],
    e:L("The Constitution sets up the government, defines it, and protects the basic rights of Americans.","La Constitución establece y define el gobierno y protege los derechos básicos.","Конституция учреждает и определяет правительство и защищает основные права.","Anayasa hükümeti kurar, tanımlar ve temel hakları korur.","संविधान सरकार स्थापित करता, परिभाषित करता और बुनियादी अधिकारों की रक्षा करता है।") },

  { cat:"gov", a:2,
    q:L("The idea of self-government is in the first three words of the Constitution. What are these words?","La idea de autogobierno está en las tres primeras palabras de la Constitución. ¿Cuáles son?","Идея самоуправления заложена в первых трёх словах Конституции. Что это за слова?","Öz-yönetim fikri Anayasa'nın ilk üç kelimesindedir. Bu kelimeler nelerdir?","स्व-शासन का विचार संविधान के पहले तीन शब्दों में है। वे शब्द क्या हैं?"),
    o:[L("We the Government","Nosotros el Gobierno","Мы — правительство","Biz Hükümet","हम सरकार"),
       L("Of the People","Del Pueblo","От народа","Halktan","जनता का"),
       L("We the People","Nosotros el Pueblo","Мы, народ","Biz Halk","हम जनता"),
       L("One Nation United","Una Nación Unida","Единая нация","Birleşik Ulus","एक संयुक्त राष्ट्र")],
    e:L("The Constitution begins with “We the People.”","La Constitución comienza con “Nosotros el Pueblo”.","Конституция начинается словами “Мы, народ”.","Anayasa “Biz Halk” ile başlar.","संविधान “हम जनता” से शुरू होता है।") },

  { cat:"gov", a:1,
    q:L("What do we call a change to the Constitution?","¿Cómo se llama un cambio a la Constitución?","Как называется изменение в Конституции?","Anayasa'da yapılan değişikliğe ne denir?","संविधान में बदलाव को क्या कहते हैं?"),
    o:[L("A bill","Un proyecto de ley","Законопроект","Tasarı","विधेयक"),
       L("An amendment","Una enmienda","Поправка","Değişiklik (amendment)","संशोधन"),
       L("A veto","Un veto","Вето","Veto","वीटो"),
       L("A clause","Una cláusula","Статья","Madde","खंड")],
    e:L("A change (or addition) to the Constitution is an amendment.","Un cambio (o adición) a la Constitución es una enmienda.","Изменение (или дополнение) Конституции — это поправка.","Anayasa'ya yapılan değişiklik bir “amendment”'tir.","संविधान में बदलाव को संशोधन कहते हैं।") },

  { cat:"gov", a:2,
    q:L("What do we call the first ten amendments to the Constitution?","¿Cómo se llaman las primeras diez enmiendas a la Constitución?","Как называются первые десять поправок к Конституции?","Anayasa'nın ilk on değişikliğine ne denir?","संविधान के पहले दस संशोधनों को क्या कहते हैं?"),
    o:[L("The Articles","Los Artículos","Статьи","Maddeler","अनुच्छेद"),
       L("The Preamble","El Preámbulo","Преамбула","Önsöz","प्रस्तावना"),
       L("The Bill of Rights","La Carta de Derechos","Билль о правах","Haklar Bildirgesi","अधिकार विधेयक"),
       L("The Federalist Papers","Los Documentos Federalistas","Записки федералиста","Federalist Yazıları","फेडरलिस्ट पेपर्स")],
    e:L("The first ten amendments are the Bill of Rights.","Las primeras diez enmiendas son la Carta de Derechos.","Первые десять поправок — это Билль о правах.","İlk on değişiklik Haklar Bildirgesi'dir.","पहले दस संशोधन अधिकार विधेयक हैं।") },

  { cat:"gov", a:0,
    q:L("How many amendments does the Constitution have?","¿Cuántas enmiendas tiene la Constitución?","Сколько поправок в Конституции?","Anayasa'da kaç değişiklik vardır?","संविधान में कितने संशोधन हैं?"),
    o:[L("Twenty-seven (27)","Veintisiete (27)","Двадцать семь (27)","Yirmi yedi (27)","सत्ताईस (27)"),
       L("Ten (10)","Diez (10)","Десять (10)","On (10)","दस (10)"),
       L("Thirteen (13)","Trece (13)","Тринадцать (13)","On üç (13)","तेरह (13)"),
       L("Fifty (50)","Cincuenta (50)","Пятьдесят (50)","Elli (50)","पचास (50)")],
    e:L("The Constitution has 27 amendments.","La Constitución tiene 27 enmiendas.","В Конституции 27 поправок.","Anayasa'da 27 değişiklik vardır.","संविधान में 27 संशोधन हैं।") },

  { cat:"gov", a:0,
    q:L("What is one right or freedom from the First Amendment?","¿Cuál es un derecho o libertad de la Primera Enmienda?","Какое право или свобода даны Первой поправкой?","Birinci Değişiklik'ten bir hak veya özgürlük nedir?","पहले संशोधन से एक अधिकार या स्वतंत्रता क्या है?"),
    o:[L("Speech","Expresión","Слово","İfade","अभिव्यक्ति"),
       L("To own a home","Poseer una casa","Владеть домом","Ev sahibi olmak","घर रखना"),
       L("Free college","Universidad gratis","Бесплатное образование","Ücretsiz üniversite","मुफ्त कॉलेज"),
       L("To drive a car","Conducir un auto","Водить машину","Araba kullanmak","कार चलाना")],
    e:L("First Amendment rights: speech, religion, assembly, press, and to petition the government.","Derechos de la Primera Enmienda: expresión, religión, reunión, prensa y peticionar al gobierno.","Права Первой поправки: слово, религия, собрания, пресса и обращение к правительству.","Birinci Değişiklik hakları: ifade, din, toplanma, basın ve hükümete dilekçe verme.","पहले संशोधन के अधिकार: अभिव्यक्ति, धर्म, सभा, प्रेस और सरकार से याचना।") },

  { cat:"gov", a:1,
    q:L("What is the economic system in the United States?","¿Cuál es el sistema económico de Estados Unidos?","Какая экономическая система в США?","ABD'nin ekonomik sistemi nedir?","संयुक्त राज्य की आर्थिक प्रणाली क्या है?"),
    o:[L("Command economy","Economía planificada","Командная экономика","Komuta ekonomisi","आदेश अर्थव्यवस्था"),
       L("Capitalist / market economy","Economía capitalista / de mercado","Капиталистическая / рыночная экономика","Kapitalist / piyasa ekonomisi","पूंजीवादी / बाज़ार अर्थव्यवस्था"),
       L("Barter economy","Economía de trueque","Бартерная экономика","Takas ekonomisi","वस्तु-विनिमय अर्थव्यवस्था"),
       L("State-owned economy","Economía estatal","Государственная экономика","Devlet mülkiyetli ekonomi","राज्य-स्वामित्व अर्थव्यवस्था")],
    e:L("The US has a capitalist (market) economy.","Estados Unidos tiene una economía capitalista (de mercado).","В США капиталистическая (рыночная) экономика.","ABD'de kapitalist (piyasa) ekonomi vardır.","अमेरिका में पूंजीवादी (बाज़ार) अर्थव्यवस्था है।") },

  { cat:"gov", a:2,
    q:L("What is the “rule of law”?","¿Qué es el “estado de derecho”?","Что такое “верховенство закона”?","“Hukukun üstünlüğü” nedir?","“कानून का शासन” क्या है?"),
    o:[L("Only judges follow the law","Solo los jueces siguen la ley","Закон соблюдают только судьи","Yasaya sadece yargıçlar uyar","केवल न्यायाधीश कानून मानते हैं"),
       L("Leaders are above the law","Los líderes están por encima de la ley","Лидеры стоят выше закона","Liderler yasanın üstündedir","नेता कानून से ऊपर हैं"),
       L("Everyone must follow the law","Todos deben obedecer la ley","Все должны соблюдать закон","Herkes yasaya uymalıdır","सभी को कानून मानना चाहिए"),
       L("The law changes daily","La ley cambia a diario","Закон меняется ежедневно","Yasa her gün değişir","कानून रोज़ बदलता है")],
    e:L("Rule of law means everyone — including leaders and government — must follow the law.","El estado de derecho: todos, incluidos líderes y gobierno, deben obedecer la ley.","Верховенство закона: все, включая лидеров и правительство, подчиняются закону.","Hukukun üstünlüğü: liderler ve hükümet dahil herkes yasaya uyar.","कानून का शासन: नेता और सरकार सहित सभी को कानून मानना चाहिए।") },

  // ---- System of Government ----
  { cat:"gov", a:1,
    q:L("How many branches does the federal government have?","¿Cuántas ramas tiene el gobierno federal?","Сколько ветвей у федерального правительства?","Federal hükümetin kaç kolu vardır?","संघीय सरकार की कितनी शाखाएँ हैं?"),
    o:[L("Two (2)","Dos (2)","Две (2)","İki (2)","दो (2)"),
       L("Three (3)","Tres (3)","Три (3)","Üç (3)","तीन (3)"),
       L("Four (4)","Cuatro (4)","Четыре (4)","Dört (4)","चार (4)"),
       L("One (1)","Una (1)","Одна (1)","Bir (1)","एक (1)")],
    e:L("Three branches: Legislative, Executive, and Judicial.","Tres ramas: Legislativa, Ejecutiva y Judicial.","Три ветви: законодательная, исполнительная и судебная.","Üç kol: Yasama, Yürütme ve Yargı.","तीन शाखाएँ: विधायी, कार्यकारी और न्यायिक।") },

  { cat:"gov", a:0,
    q:L("What stops one branch of government from becoming too powerful?","¿Qué impide que una rama del gobierno se vuelva demasiado poderosa?","Что мешает одной ветви власти стать слишком сильной?","Bir hükümet kolunun fazla güçlenmesini ne engeller?","कौन-सी चीज़ सरकार की एक शाखा को बहुत शक्तिशाली होने से रोकती है?"),
    o:[L("Checks and balances (separation of powers)","Controles y equilibrios (separación de poderes)","Сдержки и противовесы (разделение властей)","Denge ve denetleme (güçler ayrılığı)","नियंत्रण और संतुलन (शक्ति पृथक्करण)"),
       L("The President alone","Solo el Presidente","Только президент","Yalnızca Başkan","केवल राष्ट्रपति"),
       L("The military","El ejército","Армия","Ordu","सेना"),
       L("Public opinion polls","Las encuestas de opinión","Опросы общественного мнения","Kamuoyu anketleri","जनमत सर्वेक्षण")],
    e:L("Checks and balances / separation of powers keep any one branch from dominating.","Los controles y equilibrios / separación de poderes evitan el dominio de una rama.","Сдержки и противовесы / разделение властей не дают одной ветви доминировать.","Denge-denetleme / güçler ayrılığı tek bir kolun baskın olmasını önler.","नियंत्रण-संतुलन / शक्ति पृथक्करण किसी एक शाखा को हावी होने से रोकते हैं।") },

  { cat:"gov", a:2,
    q:L("Who makes federal laws?","¿Quién hace las leyes federales?","Кто принимает федеральные законы?","Federal yasaları kim yapar?","संघीय कानून कौन बनाता है?"),
    o:[L("The President","El Presidente","Президент","Başkan","राष्ट्रपति"),
       L("The Supreme Court","La Corte Suprema","Верховный суд","Yüksek Mahkeme","सर्वोच्च न्यायालय"),
       L("Congress","El Congreso","Конгресс","Kongre","कांग्रेस"),
       L("The states only","Solo los estados","Только штаты","Sadece eyaletler","केवल राज्य")],
    e:L("Congress (the Legislative branch) makes federal laws.","El Congreso (rama legislativa) hace las leyes federales.","Конгресс (законодательная ветвь) принимает федеральные законы.","Kongre (yasama kolu) federal yasaları yapar.","कांग्रेस (विधायी शाखा) संघीय कानून बनाती है।") },

  { cat:"gov", a:1,
    q:L("What are the two parts of the U.S. Congress?","¿Cuáles son las dos partes del Congreso de EE. UU.?","Из каких двух частей состоит Конгресс США?","ABD Kongresi'nin iki bölümü nedir?","अमेरिकी कांग्रेस के दो भाग क्या हैं?"),
    o:[L("The House and the Cabinet","La Cámara y el Gabinete","Палата и кабинет","Meclis ve Kabine","सदन और मंत्रिमंडल"),
       L("The Senate and the House of Representatives","El Senado y la Cámara de Representantes","Сенат и Палата представителей","Senato ve Temsilciler Meclisi","सीनेट और प्रतिनिधि सभा"),
       L("The Senate and the Supreme Court","El Senado y la Corte Suprema","Сенат и Верховный суд","Senato ve Yüksek Mahkeme","सीनेट और सर्वोच्च न्यायालय"),
       L("The States and the President","Los Estados y el Presidente","Штаты и президент","Eyaletler ve Başkan","राज्य और राष्ट्रपति")],
    e:L("Congress has two parts: the Senate and the House of Representatives.","El Congreso tiene dos partes: el Senado y la Cámara de Representantes.","Конгресс состоит из Сената и Палаты представителей.","Kongre iki bölümden oluşur: Senato ve Temsilciler Meclisi.","कांग्रेस के दो भाग हैं: सीनेट और प्रतिनिधि सभा।") },

  { cat:"gov", a:0,
    q:L("How many U.S. Senators are there?","¿Cuántos senadores de EE. UU. hay?","Сколько в США сенаторов?","Kaç ABD Senatörü vardır?","कितने अमेरिकी सीनेटर हैं?"),
    o:[L("One hundred (100)","Cien (100)","Сто (100)","Yüz (100)","एक सौ (100)"),
       L("Four hundred thirty-five (435)","Cuatrocientos treinta y cinco (435)","Четыреста тридцать пять (435)","Dört yüz otuz beş (435)","चार सौ पैंतीस (435)"),
       L("Fifty (50)","Cincuenta (50)","Пятьдесят (50)","Elli (50)","पचास (50)"),
       L("Nine (9)","Nueve (9)","Девять (9)","Dokuz (9)","नौ (9)")],
    e:L("There are 100 Senators — two from each state.","Hay 100 senadores: dos por cada estado.","100 сенаторов — по два от каждого штата.","100 Senatör vardır — her eyaletten iki.","100 सीनेटर हैं — हर राज्य से दो।") },

  { cat:"gov", a:2,
    q:L("We elect a U.S. Senator for how many years?","¿Por cuántos años elegimos a un senador?","На сколько лет избирается сенатор США?","Bir ABD Senatörünü kaç yıllığına seçeriz?","हम एक अमेरिकी सीनेटर को कितने वर्षों के लिए चुनते हैं?"),
    o:[L("Two (2)","Dos (2)","Два (2)","İki (2)","दो (2)"),
       L("Four (4)","Cuatro (4)","Четыре (4)","Dört (4)","चार (4)"),
       L("Six (6)","Seis (6)","Шесть (6)","Altı (6)","छह (6)"),
       L("Eight (8)","Ocho (8)","Восемь (8)","Sekiz (8)","आठ (8)")],
    e:L("A U.S. Senator serves a six-year term.","Un senador sirve un período de seis años.","Срок сенатора — шесть лет.","Bir Senatör altı yıllık görev yapar.","एक सीनेटर छह साल की अवधि के लिए कार्य करता है।") },

  { cat:"gov", a:1,
    q:L("How many voting members are in the House of Representatives?","¿Cuántos miembros con voto hay en la Cámara de Representantes?","Сколько голосующих членов в Палате представителей?","Temsilciler Meclisi'nde kaç oy hakkı olan üye vardır?","प्रतिनिधि सभा में कितने मतदान सदस्य हैं?"),
    o:[L("One hundred (100)","Cien (100)","Сто (100)","Yüz (100)","एक सौ (100)"),
       L("Four hundred thirty-five (435)","Cuatrocientos treinta y cinco (435)","Четыреста тридцать пять (435)","Dört yüz otuz beş (435)","चार सौ पैंतीस (435)"),
       L("Fifty (50)","Cincuenta (50)","Пятьдесят (50)","Elli (50)","पचास (50)"),
       L("Five hundred (500)","Quinientos (500)","Пятьсот (500)","Beş yüz (500)","पाँच सौ (500)")],
    e:L("The House has 435 voting members.","La Cámara tiene 435 miembros con voto.","В Палате представителей 435 голосующих членов.","Mecliste 435 oy hakkı olan üye vardır.","सभा में 435 मतदान सदस्य हैं।") },

  { cat:"gov", a:0,
    q:L("We elect a U.S. Representative for how many years?","¿Por cuántos años elegimos a un representante?","На сколько лет избирается член Палаты представителей?","Bir Temsilciyi kaç yıllığına seçeriz?","हम एक प्रतिनिधि को कितने वर्षों के लिए चुनते हैं?"),
    o:[L("Two (2)","Dos (2)","Два (2)","İki (2)","दो (2)"),
       L("Four (4)","Cuatro (4)","Четыре (4)","Dört (4)","चार (4)"),
       L("Six (6)","Seis (6)","Шесть (6)","Altı (6)","छह (6)"),
       L("Ten (10)","Diez (10)","Десять (10)","On (10)","दस (10)")],
    e:L("A U.S. Representative serves a two-year term.","Un representante sirve un período de dos años.","Срок члена Палаты представителей — два года.","Bir Temsilci iki yıllık görev yapar.","एक प्रतिनिधि दो साल की अवधि के लिए कार्य करता है।") },

  { cat:"gov", a:1,
    q:L("We elect a President for how many years?","¿Por cuántos años elegimos al Presidente?","На сколько лет избирается президент?","Başkanı kaç yıllığına seçeriz?","हम राष्ट्रपति को कितने वर्षों के लिए चुनते हैं?"),
    o:[L("Two (2)","Dos (2)","Два (2)","İki (2)","दो (2)"),
       L("Four (4)","Cuatro (4)","Четыре (4)","Dört (4)","चार (4)"),
       L("Six (6)","Seis (6)","Шесть (6)","Altı (6)","छह (6)"),
       L("Eight (8)","Ocho (8)","Восемь (8)","Sekiz (8)","आठ (8)")],
    e:L("We elect a President for four years.","Elegimos al Presidente por cuatro años.","Президента избирают на четыре года.","Başkanı dört yıllığına seçeriz.","हम राष्ट्रपति को चार साल के लिए चुनते हैं।") },

  { cat:"gov", a:2,
    q:L("Who is the Commander in Chief of the military?","¿Quién es el comandante en jefe del ejército?","Кто является главнокомандующим вооружёнными силами?","Ordunun Başkomutanı kimdir?","सेना का सर्वोच्च कमांडर कौन है?"),
    o:[L("A general","Un general","Генерал","Bir general","एक जनरल"),
       L("The Speaker of the House","El Presidente de la Cámara","Спикер Палаты представителей","Meclis Başkanı","सदन का अध्यक्ष"),
       L("The President","El Presidente","Президент","Başkan","राष्ट्रपति"),
       L("The Chief Justice","El Presidente de la Corte Suprema","Главный судья","Baş Yargıç","मुख्य न्यायाधीश")],
    e:L("The President is the Commander in Chief of the military.","El Presidente es el comandante en jefe del ejército.","Президент — главнокомандующий вооружёнными силами.","Başkan ordunun başkomutanıdır.","राष्ट्रपति सेना का सर्वोच्च कमांडर है।") },

  { cat:"gov", a:0,
    q:L("If the President can no longer serve, who becomes President?","Si el Presidente ya no puede servir, ¿quién se convierte en Presidente?","Если президент больше не может исполнять обязанности, кто становится президентом?","Başkan görevi sürdüremezse kim Başkan olur?","यदि राष्ट्रपति सेवा नहीं कर सकते, तो राष्ट्रपति कौन बनता है?"),
    o:[L("The Vice President","El Vicepresidente","Вице-президент","Başkan Yardımcısı","उपराष्ट्रपति"),
       L("The Speaker of the House","El Presidente de la Cámara","Спикер Палаты представителей","Meclis Başkanı","सदन का अध्यक्ष"),
       L("The Chief Justice","El Presidente de la Corte Suprema","Главный судья","Baş Yargıç","मुख्य न्यायाधीश"),
       L("A new election is held immediately","Se celebra una nueva elección de inmediato","Немедленно проводятся новые выборы","Hemen yeni seçim yapılır","तुरंत नया चुनाव होता है")],
    e:L("If the President can no longer serve, the Vice President becomes President.","Si el Presidente ya no puede servir, el Vicepresidente asume la presidencia.","Если президент не может исполнять обязанности, президентом становится вице-президент.","Başkan görevi sürdüremezse Başkan Yardımcısı Başkan olur.","यदि राष्ट्रपति सेवा नहीं कर सकते, तो उपराष्ट्रपति राष्ट्रपति बनते हैं।") },

  { cat:"gov", a:1,
    q:L("Who signs bills to become laws?","¿Quién firma los proyectos de ley para que se conviertan en leyes?","Кто подписывает законопроекты, чтобы они стали законами?","Tasarıların yasa olması için kim imzalar?","विधेयकों को कानून बनाने के लिए कौन हस्ताक्षर करता है?"),
    o:[L("The Chief Justice","El Presidente de la Corte Suprema","Главный судья","Baş Yargıç","मुख्य न्यायाधीश"),
       L("The President","El Presidente","Президент","Başkan","राष्ट्रपति"),
       L("The Speaker of the House","El Presidente de la Cámara","Спикер Палаты представителей","Meclis Başkanı","सदन का अध्यक्ष"),
       L("The Senate majority leader","El líder de la mayoría del Senado","Лидер большинства в Сенате","Senato çoğunluk lideri","सीनेट बहुमत नेता")],
    e:L("The President signs bills into law (and may veto them).","El Presidente firma los proyectos de ley (y puede vetarlos).","Президент подписывает законопроекты (или налагает вето).","Başkan tasarıları yasalaştırır (veto da edebilir).","राष्ट्रपति विधेयकों पर हस्ताक्षर करते हैं (और वीटो कर सकते हैं)।") },

  { cat:"gov", a:2,
    q:L("What does the President's Cabinet do?","¿Qué hace el Gabinete del Presidente?","Что делает кабинет президента?","Başkanın Kabinesi ne yapar?","राष्ट्रपति का मंत्रिमंडल क्या करता है?"),
    o:[L("Makes federal laws","Hace las leyes federales","Принимает федеральные законы","Federal yasaları yapar","संघीय कानून बनाता है"),
       L("Decides court cases","Decide casos judiciales","Решает судебные дела","Mahkeme davalarına karar verir","अदालती मामले तय करता है"),
       L("Advises the President","Asesora al Presidente","Консультирует президента","Başkana danışmanlık eder","राष्ट्रपति को सलाह देता है"),
       L("Elects Senators","Elige a los senadores","Избирает сенаторов","Senatörleri seçer","सीनेटर चुनता है")],
    e:L("The Cabinet advises the President.","El Gabinete asesora al Presidente.","Кабинет консультирует президента.","Kabine Başkana danışmanlık yapar.","मंत्रिमंडल राष्ट्रपति को सलाह देता है।") },

  { cat:"gov", a:0,
    q:L("What does the judicial branch do?","¿Qué hace la rama judicial?","Что делает судебная ветвь власти?","Yargı kolu ne yapar?","न्यायिक शाखा क्या करती है?"),
    o:[L("Reviews and explains laws","Revisa y explica las leyes","Рассматривает и толкует законы","Yasaları gözden geçirir ve açıklar","कानूनों की समीक्षा और व्याख्या करती है"),
       L("Writes new laws","Escribe leyes nuevas","Пишет новые законы","Yeni yasalar yazar","नए कानून लिखती है"),
       L("Commands the army","Comanda el ejército","Командует армией","Orduyu yönetir","सेना का नेतृत्व करती है"),
       L("Collects taxes","Recauda impuestos","Собирает налоги","Vergi toplar","कर वसूलती है")],
    e:L("The judicial branch reviews and explains laws and resolves disputes.","La rama judicial revisa y explica las leyes y resuelve disputas.","Судебная ветвь рассматривает и толкует законы, разрешает споры.","Yargı kolu yasaları yorumlar ve anlaşmazlıkları çözer.","न्यायिक शाखा कानूनों की व्याख्या करती और विवाद सुलझाती है।") },

  { cat:"gov", a:1,
    q:L("What is the highest court in the United States?","¿Cuál es el tribunal más alto de Estados Unidos?","Какой высший суд в США?","ABD'nin en yüksek mahkemesi nedir?","संयुक्त राज्य का सर्वोच्च न्यायालय कौन-सा है?"),
    o:[L("The federal district court","El tribunal de distrito federal","Федеральный окружной суд","Federal bölge mahkemesi","संघीय जिला न्यायालय"),
       L("The Supreme Court","La Corte Suprema","Верховный суд","Yüksek Mahkeme","सर्वोच्च न्यायालय"),
       L("The court of appeals","El tribunal de apelaciones","Апелляционный суд","Temyiz mahkemesi","अपील न्यायालय"),
       L("The state supreme court","La corte suprema estatal","Верховный суд штата","Eyalet yüksek mahkemesi","राज्य सर्वोच्च न्यायालय")],
    e:L("The Supreme Court is the highest court in the United States.","La Corte Suprema es el tribunal más alto.","Верховный суд — высший суд США.","Yüksek Mahkeme ABD'nin en yüksek mahkemesidir.","सर्वोच्च न्यायालय अमेरिका का उच्चतम न्यायालय है।") },

  { cat:"gov", a:2,
    q:L("How many justices are on the Supreme Court?","¿Cuántos jueces hay en la Corte Suprema?","Сколько судей в Верховном суде?","Yüksek Mahkeme'de kaç yargıç vardır?","सर्वोच्च न्यायालय में कितने न्यायाधीश हैं?"),
    o:[L("Twelve (12)","Doce (12)","Двенадцать (12)","On iki (12)","बारह (12)"),
       L("Six (6)","Seis (6)","Шесть (6)","Altı (6)","छह (6)"),
       L("Nine (9)","Nueve (9)","Девять (9)","Dokuz (9)","नौ (9)"),
       L("Fifteen (15)","Quince (15)","Пятнадцать (15)","On beş (15)","पंद्रह (15)")],
    e:L("The Supreme Court has nine (9) justices.","La Corte Suprema tiene nueve (9) jueces.","В Верховном суде девять (9) судей.","Yüksek Mahkeme'de dokuz (9) yargıç vardır.","सर्वोच्च न्यायालय में नौ (9) न्यायाधीश हैं।") },

  { cat:"gov", a:0,
    q:L("Under our Constitution, what is one power of the federal government?","Según la Constitución, ¿cuál es un poder del gobierno federal?","Согласно Конституции, какое полномочие у федерального правительства?","Anayasa'ya göre federal hükümetin bir yetkisi nedir?","संविधान के तहत संघीय सरकार की एक शक्ति क्या है?"),
    o:[L("To print money / declare war","Imprimir dinero / declarar la guerra","Печатать деньги / объявлять войну","Para basmak / savaş ilan etmek","पैसा छापना / युद्ध घोषित करना"),
       L("To issue driver's licenses","Emitir licencias de conducir","Выдавать водительские права","Ehliyet vermek","ड्राइविंग लाइसेंस जारी करना"),
       L("To provide schooling","Proveer educación","Обеспечивать образование","Eğitim sağlamak","स्कूली शिक्षा देना"),
       L("To approve local zoning","Aprobar la zonificación local","Утверждать местное зонирование","Yerel imar onayı","स्थानीय ज़ोनिंग मंज़ूरी")],
    e:L("Federal powers include printing money, declaring war, creating an army, and making treaties.","El gobierno federal puede imprimir dinero, declarar la guerra, crear un ejército y hacer tratados.","Федеральные полномочия: печатать деньги, объявлять войну, создавать армию, заключать договоры.","Federal yetkiler: para basmak, savaş ilan etmek, ordu kurmak ve antlaşma yapmak.","संघीय शक्तियाँ: पैसा छापना, युद्ध घोषित करना, सेना बनाना और संधियाँ करना।") },

  { cat:"gov", a:1,
    q:L("Under our Constitution, what is one power of the states?","Según la Constitución, ¿cuál es un poder de los estados?","Согласно Конституции, какое полномочие у штатов?","Anayasa'ya göre eyaletlerin bir yetkisi nedir?","संविधान के तहत राज्यों की एक शक्ति क्या है?"),
    o:[L("To print money","Imprimir dinero","Печатать деньги","Para basmak","पैसा छापना"),
       L("To provide schooling and issue driver's licenses","Proveer educación y emitir licencias de conducir","Обеспечивать образование и выдавать водительские права","Eğitim sağlamak ve ehliyet vermek","स्कूली शिक्षा देना और ड्राइविंग लाइसेंस जारी करना"),
       L("To declare war","Declarar la guerra","Объявлять войну","Savaş ilan etmek","युद्ध घोषित करना"),
       L("To make treaties","Hacer tratados","Заключать договоры","Antlaşma yapmak","संधियाँ करना")],
    e:L("State powers include schooling/education, police protection, driver's licenses, and zoning.","Los estados proveen educación, protección policial, licencias de conducir y zonificación.","Полномочия штатов: образование, охрана порядка, права, зонирование.","Eyalet yetkileri: eğitim, polis koruması, ehliyet ve imar.","राज्य की शक्तियाँ: शिक्षा, पुलिस सुरक्षा, ड्राइविंग लाइसेंस और ज़ोनिंग।") },

  { cat:"gov", a:2,
    q:L("What are the two major political parties in the United States?","¿Cuáles son los dos partidos políticos principales de EE. UU.?","Какие две главные политические партии в США?","ABD'deki iki büyük siyasi parti nedir?","संयुक्त राज्य में दो प्रमुख राजनीतिक दल कौन-से हैं?"),
    o:[L("Federalist and Whig","Federalista y Whig","Федералисты и виги","Federalist ve Whig","फेडरलिस्ट और व्हिग"),
       L("Labor and Green","Laborista y Verde","Лейбористы и зелёные","İşçi ve Yeşiller","लेबर और ग्रीन"),
       L("Democratic and Republican","Demócrata y Republicano","Демократы и республиканцы","Demokrat ve Cumhuriyetçi","डेमोक्रेटिक और रिपब्लिकन"),
       L("Liberal and Conservative","Liberal y Conservador","Либералы и консерваторы","Liberal ve Muhafazakâr","लिबरल और कंज़र्वेटिव")],
    e:L("The two major parties are the Democratic and Republican parties.","Los dos partidos principales son el Demócrata y el Republicano.","Две главные партии — Демократическая и Республиканская.","İki büyük parti Demokrat ve Cumhuriyetçi partilerdir.","दो प्रमुख दल डेमोक्रेटिक और रिपब्लिकन हैं।") },

  { cat:"gov", a:0,
    q:L("There are four amendments about who can vote. Describe one.","Hay cuatro enmiendas sobre quién puede votar. Describe una.","Есть четыре поправки о том, кто может голосовать. Опишите одну.","Kimin oy verebileceğine dair dört değişiklik var. Birini tarif edin.","कौन मतदान कर सकता है, इस पर चार संशोधन हैं। एक का वर्णन करें।"),
    o:[L("Citizens 18 and older can vote","Los ciudadanos de 18 años o más pueden votar","Граждане от 18 лет могут голосовать","18 yaş ve üzeri vatandaşlar oy verebilir","18 वर्ष और उससे अधिक के नागरिक मतदान कर सकते हैं"),
       L("Only landowners can vote","Solo los propietarios pueden votar","Голосуют только землевладельцы","Sadece toprak sahipleri oy verebilir","केवल भूमि-मालिक मतदान कर सकते हैं"),
       L("Only men can vote","Solo los hombres pueden votar","Голосуют только мужчины","Sadece erkekler oy verebilir","केवल पुरुष मतदान कर सकते हैं"),
       L("You must pay a poll tax to vote","Hay que pagar un impuesto para votar","Чтобы голосовать, нужно платить избирательный налог","Oy vermek için vergi ödenir","मतदान के लिए कर देना पड़ता है")],
    e:L("Any citizen 18 or older can vote; you don't need to own property or pay a poll tax; men and women may vote.","Cualquier ciudadano de 18+ puede votar; no se exige propiedad ni impuesto; votan hombres y mujeres.","Любой гражданин от 18 лет может голосовать; собственность и налог не нужны; голосуют мужчины и женщины.","18 yaş üstü her vatandaş oy verebilir; mülk veya vergi gerekmez; kadın-erkek oy verir.","18+ का कोई भी नागरिक मतदान कर सकता है; संपत्ति या कर ज़रूरी नहीं; पुरुष-महिला दोनों मतदान करते हैं।") },

  // ---- Rights and Responsibilities ----
  { cat:"gov", a:1,
    q:L("What is one responsibility that is only for U.S. citizens?","¿Cuál es una responsabilidad reservada solo para ciudadanos de EE. UU.?","Какая обязанность есть только у граждан США?","Yalnızca ABD vatandaşlarına ait bir sorumluluk nedir?","केवल अमेरिकी नागरिकों की एक ज़िम्मेदारी क्या है?"),
    o:[L("Pay taxes","Pagar impuestos","Платить налоги","Vergi ödemek","कर देना"),
       L("Serve on a jury (and vote in federal elections)","Servir en un jurado (y votar en elecciones federales)","Быть присяжным (и голосовать на федеральных выборах)","Jüri görevi yapmak (ve federal seçimlerde oy vermek)","जूरी में सेवा करना (और संघीय चुनाव में मतदान)"),
       L("Obey traffic laws","Obedecer las leyes de tránsito","Соблюдать ПДД","Trafik kurallarına uymak","यातायात नियम मानना"),
       L("Attend school","Asistir a la escuela","Посещать школу","Okula gitmek","स्कूल जाना")],
    e:L("Two duties only for citizens: serve on a jury and vote in a federal election.","Dos deberes solo de ciudadanos: servir en un jurado y votar en elecciones federales.","Только для граждан: быть присяжным и голосовать на федеральных выборах.","Yalnızca vatandaşlara: jüri görevi ve federal seçimde oy verme.","केवल नागरिकों के लिए: जूरी सेवा और संघीय चुनाव में मतदान।") },

  { cat:"gov", a:0,
    q:L("What are two rights only for U.S. citizens?","¿Cuáles son dos derechos reservados para ciudadanos de EE. UU.?","Какие два права есть только у граждан США?","Yalnızca ABD vatandaşlarına ait iki hak nedir?","केवल अमेरिकी नागरिकों के दो अधिकार क्या हैं?"),
    o:[L("Vote in a federal election and run for federal office","Votar en elecciones federales y postularse a un cargo federal","Голосовать на федеральных выборах и баллотироваться на федеральную должность","Federal seçimde oy vermek ve federal göreve aday olmak","संघीय चुनाव में मतदान और संघीय पद के लिए चुनाव लड़ना"),
       L("Free speech and freedom of religion","Libertad de expresión y de religión","Свобода слова и религии","İfade ve din özgürlüğü","अभिव्यक्ति और धर्म की स्वतंत्रता"),
       L("Own a business and travel","Tener un negocio y viajar","Владеть бизнесом и путешествовать","İş kurmak ve seyahat","व्यवसाय रखना और यात्रा"),
       L("Drive and work","Conducir y trabajar","Водить и работать","Sürmek ve çalışmak","गाड़ी चलाना और काम करना")],
    e:L("Only citizens may vote in a federal election and run for federal office.","Solo los ciudadanos pueden votar en elecciones federales y postularse a un cargo federal.","Только граждане могут голосовать на федеральных выборах и баллотироваться.","Sadece vatandaşlar federal seçimde oy verir ve federal göreve aday olur.","केवल नागरिक संघीय चुनाव में मतदान और संघीय पद के लिए चुनाव लड़ सकते हैं।") },

  { cat:"gov", a:2,
    q:L("How old do citizens have to be to vote for President?","¿Qué edad deben tener los ciudadanos para votar por el Presidente?","Со скольких лет граждане могут голосовать за президента?","Vatandaşlar Başkan için oy vermek üzere kaç yaşında olmalıdır?","राष्ट्रपति के लिए मतदान हेतु नागरिकों की आयु कितनी होनी चाहिए?"),
    o:[L("Sixteen (16)","Dieciséis (16)","Шестнадцать (16)","On altı (16)","सोलह (16)"),
       L("Twenty-one (21)","Veintiuno (21)","Двадцать один (21)","Yirmi bir (21)","इक्कीस (21)"),
       L("Eighteen (18) and older","Dieciocho (18) o más","Восемнадцать (18) и старше","On sekiz (18) ve üzeri","अठारह (18) और उससे अधिक"),
       L("Twenty-five (25)","Veinticinco (25)","Двадцать пять (25)","Yirmi beş (25)","पच्चीस (25)")],
    e:L("Citizens 18 and older can vote for President.","Los ciudadanos de 18+ pueden votar por el Presidente.","Голосовать за президента можно с 18 лет.","18 yaş ve üzeri vatandaşlar Başkan için oy verebilir.","18 वर्ष और उससे अधिक के नागरिक राष्ट्रपति के लिए मतदान कर सकते हैं।") },

  { cat:"gov", a:0,
    q:L("When is the last day you can send in federal income tax forms?","¿Cuál es el último día para enviar los formularios de impuestos federales?","Какой последний день подачи федеральной налоговой декларации?","Federal gelir vergisi formlarını göndermek için son gün nedir?","संघीय आयकर फॉर्म भेजने की अंतिम तारीख कब है?"),
    o:[L("April 15","15 de abril","15 апреля","15 Nisan","15 अप्रैल"),
       L("January 1","1 de enero","1 января","1 Ocak","1 जनवरी"),
       L("July 4","4 de julio","4 июля","4 Temmuz","4 जुलाई"),
       L("December 31","31 de diciembre","31 декабря","31 Aralık","31 दिसंबर")],
    e:L("The last day to send in federal income tax forms is April 15.","El último día para enviar los formularios es el 15 de abril.","Последний день подачи декларации — 15 апреля.","Son gün 15 Nisan'dır.","अंतिम दिन 15 अप्रैल है।") },

  { cat:"gov", a:1,
    q:L("When must all men register for the Selective Service?","¿Cuándo deben registrarse todos los hombres en el Servicio Selectivo?","Когда все мужчины должны зарегистрироваться в Selective Service?","Tüm erkekler Selective Service'e ne zaman kaydolmalıdır?","सभी पुरुषों को सिलेक्टिव सर्विस के लिए कब पंजीकरण कराना होता है?"),
    o:[L("At age 16","A los 16 años","В 16 лет","16 yaşında","16 वर्ष की आयु में"),
       L("Between ages 18 and 26","Entre los 18 y 26 años","В возрасте от 18 до 26 лет","18 ile 26 yaş arasında","18 से 26 वर्ष की आयु के बीच"),
       L("At age 30","A los 30 años","В 30 лет","30 yaşında","30 वर्ष की आयु में"),
       L("Only when drafted","Solo cuando son reclutados","Только при призыве","Sadece askere alınınca","केवल भर्ती होने पर")],
    e:L("Men ages 18 through 26 must register for the Selective Service.","Los hombres de 18 a 26 años deben registrarse en el Servicio Selectivo.","Мужчины от 18 до 26 лет обязаны зарегистрироваться.","18-26 yaş arası erkekler Selective Service'e kaydolmalıdır.","18 से 26 वर्ष के पुरुषों को पंजीकरण कराना होता है।") },

  { cat:"gov", a:2,
    q:L("What do we show loyalty to when we say the Pledge of Allegiance?","¿A qué mostramos lealtad al decir el Juramento a la Bandera?","Чему мы выражаем верность, произнося Клятву верности?","Bağlılık Yemini'ni ederken neye sadakat gösteririz?","निष्ठा की शपथ लेते समय हम किसके प्रति वफ़ादारी दिखाते हैं?"),
    o:[L("The President","Al Presidente","Президенту","Başkana","राष्ट्रपति के प्रति"),
       L("Congress","Al Congreso","Конгрессу","Kongreye","कांग्रेस के प्रति"),
       L("The United States / the flag","A Estados Unidos / la bandera","США / флагу","Birleşik Devletler'e / bayrağa","संयुक्त राज्य / ध्वज के प्रति"),
       L("The Constitution only","Solo a la Constitución","Только Конституции","Sadece Anayasa'ya","केवल संविधान के प्रति")],
    e:L("The Pledge of Allegiance shows loyalty to the United States (and the flag).","El Juramento muestra lealtad a Estados Unidos (y la bandera).","Клятва верности выражает верность США (и флагу).","Bağlılık Yemini Birleşik Devletler'e (ve bayrağa) sadakat gösterir.","निष्ठा की शपथ संयुक्त राज्य (और ध्वज) के प्रति वफ़ादारी दर्शाती है।") },

  // ---- American History: Colonial & Independence ----
  { cat:"hist", a:0,
    q:L("Who wrote the Declaration of Independence?","¿Quién escribió la Declaración de Independencia?","Кто написал Декларацию независимости?","Bağımsızlık Bildirgesi'ni kim yazdı?","स्वतंत्रता की घोषणा किसने लिखी?"),
    o:[L("Thomas Jefferson","Thomas Jefferson","Томас Джефферсон","Thomas Jefferson","थॉमस जेफरसन"),
       L("George Washington","George Washington","Джордж Вашингтон","George Washington","जॉर्ज वॉशिंगटन"),
       L("Benjamin Franklin","Benjamin Franklin","Бенджамин Франклин","Benjamin Franklin","बेंजामिन फ्रैंकलिन"),
       L("Abraham Lincoln","Abraham Lincoln","Авраам Линкольн","Abraham Lincoln","अब्राहम लिंकन")],
    e:L("Thomas Jefferson wrote the Declaration of Independence.","Thomas Jefferson escribió la Declaración de Independencia.","Декларацию независимости написал Томас Джефферсон.","Bağımsızlık Bildirgesi'ni Thomas Jefferson yazdı.","स्वतंत्रता की घोषणा थॉमस जेफरसन ने लिखी।") },

  { cat:"hist", a:1,
    q:L("When was the Declaration of Independence adopted?","¿Cuándo se adoptó la Declaración de Independencia?","Когда была принята Декларация независимости?","Bağımsızlık Bildirgesi ne zaman kabul edildi?","स्वतंत्रता की घोषणा कब अपनाई गई?"),
    o:[L("July 4, 1789","4 de julio de 1789","4 июля 1789","4 Temmuz 1789","4 जुलाई 1789"),
       L("July 4, 1776","4 de julio de 1776","4 июля 1776","4 Temmuz 1776","4 जुलाई 1776"),
       L("July 4, 1804","4 de julio de 1804","4 июля 1804","4 Temmuz 1804","4 जुलाई 1804"),
       L("July 4, 1812","4 de julio de 1812","4 июля 1812","4 Temmuz 1812","4 जुलाई 1812")],
    e:L("The Declaration of Independence was adopted on July 4, 1776.","La Declaración se adoptó el 4 de julio de 1776.","Декларация независимости принята 4 июля 1776 года.","Bağımsızlık Bildirgesi 4 Temmuz 1776'da kabul edildi.","स्वतंत्रता की घोषणा 4 जुलाई 1776 को अपनाई गई।") },

  { cat:"hist", a:2,
    q:L("What did the Declaration of Independence do?","¿Qué hizo la Declaración de Independencia?","Что сделала Декларация независимости?","Bağımsızlık Bildirgesi ne yaptı?","स्वतंत्रता की घोषणा ने क्या किया?"),
    o:[L("Freed the slaves","Liberó a los esclavos","Освободила рабов","Köleleri özgür bıraktı","दासों को मुक्त किया"),
       L("Set up the Supreme Court","Estableció la Corte Suprema","Учредила Верховный суд","Yüksek Mahkeme'yi kurdu","सर्वोच्च न्यायालय बनाया"),
       L("Announced our independence from Great Britain","Anunció nuestra independencia de Gran Bretaña","Провозгласила независимость от Великобритании","Büyük Britanya'dan bağımsızlığımızı ilan etti","ग्रेट ब्रिटेन से हमारी स्वतंत्रता की घोषणा की"),
       L("Created the 50 states","Creó los 50 estados","Создала 50 штатов","50 eyaleti kurdu","50 राज्य बनाए")],
    e:L("The Declaration of Independence announced our independence from Great Britain.","La Declaración anunció nuestra independencia de Gran Bretaña.","Декларация провозгласила независимость от Великобритании.","Bildirge Büyük Britanya'dan bağımsızlığı ilan etti.","घोषणा ने ग्रेट ब्रिटेन से स्वतंत्रता की घोषणा की।") },

  { cat:"hist", a:0,
    q:L("There were 13 original states. Name one.","Hubo 13 estados originales. Nombra uno.","Было 13 первоначальных штатов. Назовите один.","13 kurucu eyalet vardı. Birini söyleyin.","13 मूल राज्य थे। एक का नाम बताएं।"),
    o:[L("Virginia","Virginia","Виргиния","Virginia","वर्जीनिया"),
       L("California","California","Калифорния","Kaliforniya","कैलिफ़ोर्निया"),
       L("Texas","Texas","Техас","Teksas","टेक्सास"),
       L("Florida","Florida","Флорида","Florida","फ्लोरिडा")],
    e:L("Original states include Virginia, New York, Massachusetts, Pennsylvania, Georgia, and others.","Los estados originales incluyen Virginia, Nueva York, Massachusetts, Pensilvania, Georgia y otros.","Среди первых штатов — Виргиния, Нью-Йорк, Массачусетс, Пенсильвания, Джорджия и др.","Kurucu eyaletler: Virginia, New York, Massachusetts, Pennsylvania, Georgia ve diğerleri.","मूल राज्यों में वर्जीनिया, न्यूयॉर्क, मैसाचुसेट्स, पेंसिल्वेनिया, जॉर्जिया आदि शामिल हैं।") },

  { cat:"hist", a:1,
    q:L("When was the Constitution written?","¿Cuándo se escribió la Constitución?","Когда была написана Конституция?","Anayasa ne zaman yazıldı?","संविधान कब लिखा गया?"),
    o:[L("1776","1776","1776","1776","1776"),
       L("1787","1787","1787","1787","1787"),
       L("1791","1791","1791","1791","1791"),
       L("1812","1812","1812","1812","1812")],
    e:L("The Constitution was written in 1787.","La Constitución se escribió en 1787.","Конституция была написана в 1787 году.","Anayasa 1787'de yazıldı.","संविधान 1787 में लिखा गया।") },

  { cat:"hist", a:2,
    q:L("Who is called the “Father of Our Country”?","¿Quién es llamado el “Padre de Nuestra Patria”?","Кого называют “Отцом нашей страны”?","“Ülkemizin Babası” olarak kim anılır?","“हमारे देश के पिता” किसे कहा जाता है?"),
    o:[L("Thomas Jefferson","Thomas Jefferson","Томас Джефферсон","Thomas Jefferson","थॉमस जेफरसन"),
       L("Benjamin Franklin","Benjamin Franklin","Бенджамин Франклин","Benjamin Franklin","बेंजामिन फ्रैंकलिन"),
       L("George Washington","George Washington","Джордж Вашингтон","George Washington","जॉर्ज वॉशिंगटन"),
       L("John Adams","John Adams","Джон Адамс","John Adams","जॉन एडम्स")],
    e:L("George Washington is the “Father of Our Country” and the first President.","George Washington es el “Padre de Nuestra Patria” y el primer Presidente.","Джордж Вашингтон — “Отец страны” и первый президент.","George Washington “Ülkemizin Babası” ve ilk Başkandır.","जॉर्ज वॉशिंगटन “देश के पिता” और पहले राष्ट्रपति हैं।") },

  { cat:"hist", a:0,
    q:L("Who was the first President?","¿Quién fue el primer Presidente?","Кто был первым президентом?","İlk Başkan kimdi?","पहले राष्ट्रपति कौन थे?"),
    o:[L("George Washington","George Washington","Джордж Вашингтон","George Washington","जॉर्ज वॉशिंगटन"),
       L("Thomas Jefferson","Thomas Jefferson","Томас Джефферсон","Thomas Jefferson","थॉमस जेफरसन"),
       L("Abraham Lincoln","Abraham Lincoln","Авраам Линкольн","Abraham Lincoln","अब्राहम लिंकन"),
       L("John Adams","John Adams","Джон Адамс","John Adams","जॉन एडम्स")],
    e:L("George Washington was the first President.","George Washington fue el primer Presidente.","Джордж Вашингтон был первым президентом.","George Washington ilk Başkandı.","जॉर्ज वॉशिंगटन पहले राष्ट्रपति थे।") },

  { cat:"hist", a:1,
    q:L("The Federalist Papers supported the Constitution. Name one writer.","Los Documentos Federalistas apoyaron la Constitución. Nombra un autor.","“Записки федералиста” поддерживали Конституцию. Назовите одного автора.","Federalist Yazıları Anayasa'yı destekledi. Bir yazar söyleyin.","फेडरलिस्ट पेपर्स ने संविधान का समर्थन किया। एक लेखक का नाम बताएं।"),
    o:[L("Thomas Jefferson","Thomas Jefferson","Томас Джефферсон","Thomas Jefferson","थॉमस जेफरसन"),
       L("(James) Madison","(James) Madison","(Джеймс) Мэдисон","(James) Madison","(जेम्स) मैडिसन"),
       L("George Washington","George Washington","Джордж Вашингтон","George Washington","जॉर्ज वॉशिंगटन"),
       L("Patrick Henry","Patrick Henry","Патрик Генри","Patrick Henry","पैट्रिक हेनरी")],
    e:L("The Federalist Papers were written by Madison, Hamilton, and Jay (as “Publius”).","Los Federalistas fueron escritos por Madison, Hamilton y Jay (como “Publius”).","“Записки федералиста” написали Мэдисон, Гамильтон и Джей (под именем “Публий”).","Federalist Yazıları'nı Madison, Hamilton ve Jay (“Publius”) yazdı.","फेडरलिस्ट पेपर्स मैडिसन, हैमिल्टन और जे (“पब्लियस”) ने लिखे।") },

  { cat:"hist", a:2,
    q:L("Benjamin Franklin is famous for what?","¿Por qué es famoso Benjamin Franklin?","Чем знаменит Бенджамин Франклин?","Benjamin Franklin neyle ünlüdür?","बेंजामिन फ्रैंकलिन किसके लिए प्रसिद्ध हैं?"),
    o:[L("Being the first President","Ser el primer Presidente","Был первым президентом","İlk Başkan olmasıyla","पहले राष्ट्रपति होने के लिए"),
       L("Writing the national anthem","Escribir el himno nacional","Написал гимн","Milli marşı yazmasıyla","राष्ट्रगान लिखने के लिए"),
       L("Being the first Postmaster General / a U.S. diplomat","Ser el primer director de correos / diplomático","Первый генеральный почтмейстер / дипломат США","İlk Posta Genel Müdürü / ABD diplomatı olması","पहले पोस्टमास्टर जनरल / अमेरिकी राजनयिक"),
       L("Leading the Civil War","Liderar la Guerra Civil","Возглавлял Гражданскую войну","İç Savaş'ı yönetmesiyle","गृहयुद्ध का नेतृत्व करने के लिए")],
    e:L("Franklin was a U.S. diplomat, the first Postmaster General, and oldest delegate at the Constitutional Convention.","Franklin fue diplomático, primer director de correos y el delegado de mayor edad en la Convención.","Франклин — дипломат, первый генеральный почтмейстер, старейший делегат Конвента.","Franklin diplomat, ilk Posta Genel Müdürü ve Konvansiyon'un en yaşlı delegesiydi.","फ्रैंकलिन राजनयिक, पहले पोस्टमास्टर जनरल और संविधान सम्मेलन के सबसे बुज़ुर्ग प्रतिनिधि थे।") },

  // ---- 1800s ----
  { cat:"hist", a:1,
    q:L("What territory did the United States buy from France in 1803?","¿Qué territorio compró Estados Unidos a Francia en 1803?","Какую территорию США купили у Франции в 1803 году?","ABD 1803'te Fransa'dan hangi toprağı satın aldı?","1803 में अमेरिका ने फ्रांस से कौन-सा क्षेत्र खरीदा?"),
    o:[L("Alaska","Alaska","Аляска","Alaska","अलास्का"),
       L("The Louisiana Territory","El Territorio de Luisiana","Территория Луизиана","Louisiana Toprakları","लुइसियाना क्षेत्र"),
       L("Florida","Florida","Флорида","Florida","फ्लोरिडा"),
       L("Texas","Texas","Техас","Teksas","टेक्सास")],
    e:L("The U.S. bought the Louisiana Territory from France in 1803.","EE. UU. compró el Territorio de Luisiana a Francia en 1803.","США купили территорию Луизиана у Франции в 1803 году.","ABD 1803'te Louisiana topraklarını Fransa'dan aldı.","अमेरिका ने 1803 में फ्रांस से लुइसियाना क्षेत्र खरीदा।") },

  { cat:"hist", a:0,
    q:L("Name one war fought by the United States in the 1800s.","Nombra una guerra librada por EE. UU. en el siglo XIX.","Назовите одну войну США в XIX веке.","ABD'nin 1800'lerde yaptığı bir savaşı söyleyin.","1800 के दशक में अमेरिका द्वारा लड़ा गया एक युद्ध बताएं।"),
    o:[L("The Civil War","La Guerra Civil","Гражданская война","İç Savaş","गृहयुद्ध"),
       L("World War I","La Primera Guerra Mundial","Первая мировая война","Birinci Dünya Savaşı","प्रथम विश्व युद्ध"),
       L("World War II","La Segunda Guerra Mundial","Вторая мировая война","İkinci Dünya Savaşı","द्वितीय विश्व युद्ध"),
       L("The Vietnam War","La Guerra de Vietnam","Война во Вьетнаме","Vietnam Savaşı","वियतनाम युद्ध")],
    e:L("1800s wars include the War of 1812, the Mexican-American War, the Civil War, and the Spanish-American War.","Guerras del siglo XIX: Guerra de 1812, Guerra México-Estados Unidos, Guerra Civil y Guerra Hispano-Estadounidense.","Войны XIX века: война 1812 года, мексикано-американская, Гражданская, испано-американская.","1800'ler savaşları: 1812 Savaşı, Meksika-Amerika Savaşı, İç Savaş, İspanya-Amerika Savaşı.","1800 के युद्ध: 1812 का युद्ध, मैक्सिकन-अमेरिकी युद्ध, गृहयुद्ध, स्पेनी-अमेरिकी युद्ध।") },

  { cat:"hist", a:2,
    q:L("Name one problem that led to the Civil War.","Nombra un problema que llevó a la Guerra Civil.","Назовите одну причину Гражданской войны.","İç Savaş'a yol açan bir sorunu söyleyin.","गृहयुद्ध का कारण बना एक समस्या बताएं।"),
    o:[L("High taxes on tea","Altos impuestos al té","Высокие налоги на чай","Çaya yüksek vergi","चाय पर ऊँचा कर"),
       L("A foreign invasion","Una invasión extranjera","Иностранное вторжение","Yabancı işgali","विदेशी आक्रमण"),
       L("Slavery","La esclavitud","Рабство","Kölelik","दासता"),
       L("Lack of a flag","La falta de bandera","Отсутствие флага","Bayrak olmaması","ध्वज का अभाव")],
    e:L("The Civil War was caused by slavery, economic reasons, and states' rights.","La Guerra Civil se debió a la esclavitud, razones económicas y los derechos de los estados.","Причины Гражданской войны: рабство, экономика и права штатов.","İç Savaş'ın nedenleri: kölelik, ekonomik nedenler ve eyalet hakları.","गृहयुद्ध के कारण: दासता, आर्थिक कारण और राज्यों के अधिकार।") },

  { cat:"hist", a:0,
    q:L("What did Abraham Lincoln do?","¿Qué hizo Abraham Lincoln?","Что сделал Авраам Линкольн?","Abraham Lincoln ne yaptı?","अब्राहम लिंकन ने क्या किया?"),
    o:[L("Freed the slaves and preserved the Union","Liberó a los esclavos y preservó la Unión","Освободил рабов и сохранил Союз","Köleleri özgürleştirdi ve Birliği korudu","दासों को मुक्त किया और संघ को बचाया"),
       L("Wrote the Constitution","Escribió la Constitución","Написал Конституцию","Anayasa'yı yazdı","संविधान लिखा"),
       L("Discovered electricity","Descubrió la electricidad","Открыл электричество","Elektriği keşfetti","बिजली की खोज की"),
       L("Bought Alaska","Compró Alaska","Купил Аляску","Alaska'yı satın aldı","अलास्का खरीदा")],
    e:L("Lincoln freed the slaves (Emancipation Proclamation), saved/preserved the Union, and led during the Civil War.","Lincoln liberó a los esclavos, preservó la Unión y lideró durante la Guerra Civil.","Линкольн освободил рабов, сохранил Союз и руководил во время Гражданской войны.","Lincoln köleleri özgürleştirdi, Birliği korudu ve İç Savaş'ta liderlik etti.","लिंकन ने दासों को मुक्त किया, संघ को बचाया और गृहयुद्ध में नेतृत्व किया।") },

  { cat:"hist", a:1,
    q:L("What did the Emancipation Proclamation do?","¿Qué hizo la Proclamación de Emancipación?","Что сделала Прокламация об освобождении рабов?","Özgürlük Bildirgesi ne yaptı?","मुक्ति घोषणा ने क्या किया?"),
    o:[L("Ended World War I","Terminó la Primera Guerra Mundial","Завершила Первую мировую войну","Birinci Dünya Savaşı'nı bitirdi","प्रथम विश्व युद्ध समाप्त किया"),
       L("Freed the slaves","Liberó a los esclavos","Освободила рабов","Köleleri özgür bıraktı","दासों को मुक्त किया"),
       L("Created the income tax","Creó el impuesto sobre la renta","Ввела подоходный налог","Gelir vergisini getirdi","आयकर बनाया"),
       L("Gave women the vote","Dio el voto a las mujeres","Дала женщинам право голоса","Kadınlara oy hakkı verdi","महिलाओं को मतदान का अधिकार दिया")],
    e:L("The Emancipation Proclamation freed the slaves.","La Proclamación de Emancipación liberó a los esclavos.","Прокламация об освобождении освободила рабов.","Özgürlük Bildirgesi köleleri özgür bıraktı.","मुक्ति घोषणा ने दासों को मुक्त किया।") },

  // ---- 1900s & Recent ----
  { cat:"hist", a:0,
    q:L("Name one war fought by the United States in the 1900s.","Nombra una guerra librada por EE. UU. en el siglo XX.","Назовите одну войну США в XX веке.","ABD'nin 1900'lerde yaptığı bir savaşı söyleyin.","1900 के दशक में अमेरिका द्वारा लड़ा गया एक युद्ध बताएं।"),
    o:[L("World War II","La Segunda Guerra Mundial","Вторая мировая война","İkinci Dünya Savaşı","द्वितीय विश्व युद्ध"),
       L("The Civil War","La Guerra Civil","Гражданская война","İç Savaş","गृहयुद्ध"),
       L("The War of 1812","La Guerra de 1812","Война 1812 года","1812 Savaşı","1812 का युद्ध"),
       L("The Revolutionary War","La Guerra de Independencia","Война за независимость","Bağımsızlık Savaşı","क्रांतिकारी युद्ध")],
    e:L("1900s wars: World War I, World War II, the Korean War, the Vietnam War, and the (Persian) Gulf War.","Guerras del siglo XX: Primera y Segunda Guerra Mundial, Corea, Vietnam y Guerra del Golfo.","Войны XX века: Первая и Вторая мировые, Корейская, Вьетнамская, война в Заливе.","1900'ler savaşları: I. ve II. Dünya Savaşı, Kore, Vietnam ve (Basra) Körfez Savaşı.","1900 के युद्ध: प्रथम-द्वितीय विश्व युद्ध, कोरिया, वियतनाम और खाड़ी युद्ध।") },

  { cat:"hist", a:1,
    q:L("Who did the United States fight in World War II?","¿Contra quién luchó Estados Unidos en la Segunda Guerra Mundial?","С кем США воевали во Второй мировой войне?","ABD İkinci Dünya Savaşı'nda kime karşı savaştı?","द्वितीय विश्व युद्ध में अमेरिका किससे लड़ा?"),
    o:[L("Britain, France, and Canada","Gran Bretaña, Francia y Canadá","Британия, Франция и Канада","Britanya, Fransa ve Kanada","ब्रिटेन, फ्रांस और कनाडा"),
       L("Japan, Germany, and Italy","Japón, Alemania e Italia","Япония, Германия и Италия","Japonya, Almanya ve İtalya","जापान, जर्मनी और इटली"),
       L("Russia and China","Rusia y China","Россия и Китай","Rusya ve Çin","रूस और चीन"),
       L("Mexico and Spain","México y España","Мексика и Испания","Meksika ve İspanya","मेक्सिको और स्पेन")],
    e:L("In World War II, the United States fought Japan, Germany, and Italy.","En la Segunda Guerra Mundial, EE. UU. luchó contra Japón, Alemania e Italia.","Во Второй мировой войне США воевали с Японией, Германией и Италией.","II. Dünya Savaşı'nda ABD Japonya, Almanya ve İtalya'ya karşı savaştı.","द्वितीय विश्व युद्ध में अमेरिका जापान, जर्मनी और इटली से लड़ा।") },

  { cat:"hist", a:2,
    q:L("During the Cold War, what was the main concern of the United States?","Durante la Guerra Fría, ¿cuál era la principal preocupación de EE. UU.?","Что было главной заботой США во время холодной войны?","Soğuk Savaş sırasında ABD'nin başlıca endişesi neydi?","शीत युद्ध के दौरान अमेरिका की मुख्य चिंता क्या थी?"),
    o:[L("Terrorism","El terrorismo","Терроризм","Terörizm","आतंकवाद"),
       L("Climate change","El cambio climático","Изменение климата","İklim değişikliği","जलवायु परिवर्तन"),
       L("Communism","El comunismo","Коммунизм","Komünizm","साम्यवाद"),
       L("Slavery","La esclavitud","Рабство","Kölelik","दासता")],
    e:L("During the Cold War, the main concern of the United States was Communism.","Durante la Guerra Fría, la principal preocupación fue el comunismo.","Главной заботой США в холодную войну был коммунизм.","Soğuk Savaş'ta ABD'nin başlıca endişesi komünizmdi.","शीत युद्ध में अमेरिका की मुख्य चिंता साम्यवाद थी।") },

  { cat:"hist", a:0,
    q:L("What movement tried to end racial discrimination?","¿Qué movimiento intentó terminar con la discriminación racial?","Какое движение пыталось покончить с расовой дискриминацией?","Hangi hareket ırk ayrımcılığını sona erdirmeye çalıştı?","किस आंदोलन ने नस्लीय भेदभाव समाप्त करने का प्रयास किया?"),
    o:[L("The civil rights movement","El movimiento por los derechos civiles","Движение за гражданские права","Sivil haklar hareketi","नागरिक अधिकार आंदोलन"),
       L("The temperance movement","El movimiento de la templanza","Движение трезвости","Yeşilay hareketi","संयम आंदोलन"),
       L("The labor movement","El movimiento obrero","Рабочее движение","İşçi hareketi","श्रमिक आंदोलन"),
       L("The space race","La carrera espacial","Космическая гонка","Uzay yarışı","अंतरिक्ष दौड़")],
    e:L("The civil rights movement worked to end racial discrimination.","El movimiento por los derechos civiles buscó terminar con la discriminación racial.","Движение за гражданские права боролось с расовой дискриминацией.","Sivil haklar hareketi ırk ayrımcılığını bitirmeye çalıştı.","नागरिक अधिकार आंदोलन ने नस्लीय भेदभाव समाप्त करने का काम किया।") },

  { cat:"hist", a:1,
    q:L("What did Martin Luther King, Jr. do?","¿Qué hizo Martin Luther King, Jr.?","Что сделал Мартин Лютер Кинг-младший?","Martin Luther King Jr. ne yaptı?","मार्टिन लूथर किंग जूनियर ने क्या किया?"),
    o:[L("He was the first President","Fue el primer Presidente","Был первым президентом","İlk Başkandı","वे पहले राष्ट्रपति थे"),
       L("He fought for civil rights / equality for all Americans","Luchó por los derechos civiles / la igualdad de todos los estadounidenses","Боролся за гражданские права и равенство всех американцев","Tüm Amerikalılar için sivil haklar/eşitlik için mücadele etti","सभी अमेरिकियों के नागरिक अधिकार/समानता के लिए लड़े"),
       L("He wrote the Constitution","Escribió la Constitución","Написал Конституцию","Anayasa'yı yazdı","संविधान लिखा"),
       L("He discovered America","Descubrió América","Открыл Америку","Amerika'yı keşfetti","अमेरिका की खोज की")],
    e:L("Martin Luther King, Jr. fought for civil rights and equality for all Americans.","Martin Luther King, Jr. luchó por los derechos civiles y la igualdad.","Мартин Лютер Кинг-младший боролся за гражданские права и равенство.","Martin Luther King Jr. sivil haklar ve eşitlik için mücadele etti.","मार्टिन लूथर किंग जूनियर ने नागरिक अधिकार और समानता के लिए संघर्ष किया।") },

  { cat:"hist", a:2,
    q:L("What major event happened on September 11, 2001?","¿Qué evento importante ocurrió el 11 de septiembre de 2001?","Какое крупное событие произошло 11 сентября 2001 года?","11 Eylül 2001'de hangi büyük olay yaşandı?","11 सितंबर 2001 को कौन-सी बड़ी घटना हुई?"),
    o:[L("The Civil War ended","Terminó la Guerra Civil","Закончилась Гражданская война","İç Savaş bitti","गृहयुद्ध समाप्त हुआ"),
       L("The Constitution was signed","Se firmó la Constitución","Подписали Конституцию","Anayasa imzalandı","संविधान पर हस्ताक्षर हुए"),
       L("Terrorists attacked the United States","Terroristas atacaron Estados Unidos","Террористы атаковали США","Teröristler ABD'ye saldırdı","आतंकवादियों ने अमेरिका पर हमला किया"),
       L("Men landed on the moon","El hombre llegó a la Luna","Человек высадился на Луне","İnsan Ay'a ayak bastı","चंद्रमा पर मनुष्य उतरे")],
    e:L("On September 11, 2001, terrorists attacked the United States.","El 11 de septiembre de 2001, terroristas atacaron Estados Unidos.","11 сентября 2001 года террористы атаковали США.","11 Eylül 2001'de teröristler ABD'ye saldırdı.","11 सितंबर 2001 को आतंकवादियों ने अमेरिका पर हमला किया।") },

  { cat:"hist", a:0,
    q:L("Name one American Indian tribe in the United States.","Nombra una tribu indígena de Estados Unidos.","Назовите одно индейское племя в США.","ABD'de bir Kızılderili kabilesi söyleyin.","अमेरिका की एक अमेरिकी इंडियन जनजाति बताएं।"),
    o:[L("Cherokee","Cherokee","Чероки","Cherokee","चेरोकी"),
       L("Aztec","Azteca","Ацтеки","Aztek","एज़्टेक"),
       L("Maya","Maya","Майя","Maya","माया"),
       L("Inca","Inca","Инки","İnka","इंका")],
    e:L("Tribes include Cherokee, Navajo, Sioux, Apache, Iroquois, and many others.","Las tribus incluyen Cherokee, Navajo, Sioux, Apache, Iroquois y muchas más.","Племена: чероки, навахо, сиу, апачи, ирокезы и многие другие.","Kabileler: Cherokee, Navajo, Sioux, Apache, Iroquois ve daha fazlası.","जनजातियाँ: चेरोकी, नवाहो, सिओक्स, अपाचे, इरोक्वाई आदि।") },

  // ---- Symbols & Holidays ----
  { cat:"sym", a:1,
    q:L("Name one of the two longest rivers in the United States.","Nombra uno de los dos ríos más largos de Estados Unidos.","Назовите одну из двух самых длинных рек США.","ABD'nin en uzun iki nehrinden birini söyleyin.","अमेरिका की दो सबसे लंबी नदियों में से एक बताएं।"),
    o:[L("The Colorado River","El río Colorado","Река Колорадо","Colorado Nehri","कोलोराडो नदी"),
       L("The Mississippi (or Missouri) River","El río Misisipi (o Misuri)","Река Миссисипи (или Миссури)","Mississippi (veya Missouri) Nehri","मिसिसिपी (या मिसौरी) नदी"),
       L("The Rio Grande","El río Bravo","Рио-Гранде","Rio Grande","रियो ग्रांडे"),
       L("The Hudson River","El río Hudson","Река Гудзон","Hudson Nehri","हडसन नदी")],
    e:L("The two longest rivers are the Missouri and the Mississippi.","Los dos ríos más largos son el Misuri y el Misisipi.","Самые длинные реки — Миссури и Миссисипи.","En uzun iki nehir Missouri ve Mississippi'dir.","दो सबसे लंबी नदियाँ मिसौरी और मिसिसिपी हैं।") },

  { cat:"sym", a:0,
    q:L("What ocean is on the West Coast of the United States?","¿Qué océano está en la costa oeste de Estados Unidos?","Какой океан омывает Западное побережье США?","ABD'nin Batı Kıyısı'nda hangi okyanus vardır?","अमेरिका के पश्चिमी तट पर कौन-सा महासागर है?"),
    o:[L("The Pacific Ocean","El océano Pacífico","Тихий океан","Pasifik Okyanusu","प्रशांत महासागर"),
       L("The Atlantic Ocean","El océano Atlántico","Атлантический океан","Atlas Okyanusu","अटलांटिक महासागर"),
       L("The Indian Ocean","El océano Índico","Индийский океан","Hint Okyanusu","हिंद महासागर"),
       L("The Arctic Ocean","El océano Ártico","Северный Ледовитый океан","Kuzey Buz Denizi","आर्कटिक महासागर")],
    e:L("The Pacific Ocean is on the West Coast (the Atlantic is on the East Coast).","El océano Pacífico está en la costa oeste (el Atlántico en la este).","На Западном побережье — Тихий океан (на Восточном — Атлантический).","Batı Kıyısı'nda Pasifik (Doğu'da Atlas) Okyanusu vardır.","पश्चिमी तट पर प्रशांत महासागर है (पूर्वी पर अटलांटिक)।") },

  { cat:"sym", a:2,
    q:L("What is the capital of the United States?","¿Cuál es la capital de Estados Unidos?","Какая столица США?","ABD'nin başkenti neresidir?","संयुक्त राज्य की राजधानी क्या है?"),
    o:[L("New York City","Nueva York","Нью-Йорк","New York","न्यूयॉर्क"),
       L("Philadelphia","Filadelfia","Филадельфия","Philadelphia","फिलाडेल्फिया"),
       L("Washington, D.C.","Washington, D.C.","Вашингтон, округ Колумбия","Washington, D.C.","वॉशिंगटन, डी.सी."),
       L("Boston","Boston","Бостон","Boston","बोस्टन")],
    e:L("The capital of the United States is Washington, D.C.","La capital de Estados Unidos es Washington, D.C.","Столица США — Вашингтон, округ Колумбия.","ABD'nin başkenti Washington, D.C.'dir.","अमेरिका की राजधानी वॉशिंगटन, डी.सी. है।") },

  { cat:"sym", a:0,
    q:L("Where is the Statue of Liberty?","¿Dónde está la Estatua de la Libertad?","Где находится Статуя Свободы?","Özgürlük Heykeli nerededir?","स्वतंत्रता की मूर्ति कहाँ है?"),
    o:[L("New York (Harbor) / Liberty Island","Nueva York (puerto) / Isla de la Libertad","Нью-Йорк (гавань) / остров Либерти","New York (Limanı) / Liberty Adası","न्यूयॉर्क (बंदरगाह) / लिबर्टी द्वीप"),
       L("Washington, D.C.","Washington, D.C.","Вашингтон, округ Колумбия","Washington, D.C.","वॉशिंगटन, डी.सी."),
       L("Boston Harbor","El puerto de Boston","Бостонская гавань","Boston Limanı","बोस्टन बंदरगाह"),
       L("San Francisco Bay","La bahía de San Francisco","Залив Сан-Франциско","San Francisco Körfezi","सैन फ्रांसिस्को खाड़ी")],
    e:L("The Statue of Liberty is in New York Harbor (on Liberty Island).","La Estatua de la Libertad está en el puerto de Nueva York (Isla de la Libertad).","Статуя Свободы — в гавани Нью-Йорка (остров Либерти).","Özgürlük Heykeli New York Limanı'ndadır (Liberty Adası).","स्वतंत्रता की मूर्ति न्यूयॉर्क बंदरगाह (लिबर्टी द्वीप) पर है।") },

  { cat:"sym", a:1,
    q:L("Why does the flag have 13 stripes?","¿Por qué la bandera tiene 13 franjas?","Почему на флаге 13 полос?","Bayrakta neden 13 şerit var?","ध्वज में 13 धारियाँ क्यों हैं?"),
    o:[L("Because there are 13 amendments","Porque hay 13 enmiendas","Потому что 13 поправок","13 değişiklik olduğu için","क्योंकि 13 संशोधन हैं"),
       L("Because there were 13 original colonies","Porque hubo 13 colonias originales","Потому что было 13 первоначальных колоний","13 kurucu koloni olduğu için","क्योंकि 13 मूल उपनिवेश थे"),
       L("Because of 13 Presidents","Por 13 presidentes","Из-за 13 президентов","13 Başkan olduğu için","क्योंकि 13 राष्ट्रपति थे"),
       L("For the 13 branches of government","Por las 13 ramas del gobierno","Из-за 13 ветвей власти","13 hükümet kolu için","13 सरकारी शाखाओं के लिए")],
    e:L("The flag has 13 stripes for the 13 original colonies.","La bandera tiene 13 franjas por las 13 colonias originales.","13 полос символизируют 13 первоначальных колоний.","Bayraktaki 13 şerit 13 kurucu koloniyi temsil eder.","ध्वज की 13 धारियाँ 13 मूल उपनिवेशों को दर्शाती हैं।") },

  { cat:"sym", a:2,
    q:L("Why does the flag have 50 stars?","¿Por qué la bandera tiene 50 estrellas?","Почему на флаге 50 звёзд?","Bayrakta neden 50 yıldız var?","ध्वज में 50 सितारे क्यों हैं?"),
    o:[L("One for each President","Una por cada Presidente","По одной за каждого президента","Her Başkan için bir tane","हर राष्ट्रपति के लिए एक"),
       L("One for each amendment","Una por cada enmienda","По одной за каждую поправку","Her değişiklik için bir tane","हर संशोधन के लिए एक"),
       L("One for each state","Una por cada estado","По одной за каждый штат","Her eyalet için bir tane","हर राज्य के लिए एक"),
       L("One for each war","Una por cada guerra","По одной за каждую войну","Her savaş için bir tane","हर युद्ध के लिए एक")],
    e:L("The flag has 50 stars — one for each state.","La bandera tiene 50 estrellas, una por cada estado.","На флаге 50 звёзд — по одной за каждый штат.","Bayrakta 50 yıldız vardır — her eyalet için bir tane.","ध्वज में 50 सितारे हैं — हर राज्य के लिए एक।") },

  { cat:"sym", a:0,
    q:L("What is the name of the national anthem?","¿Cómo se llama el himno nacional?","Как называется государственный гимн?","Milli marşın adı nedir?","राष्ट्रगान का नाम क्या है?"),
    o:[L("The Star-Spangled Banner","The Star-Spangled Banner","“Star-Spangled Banner”","The Star-Spangled Banner","द स्टार-स्पैंगल्ड बैनर"),
       L("America the Beautiful","America the Beautiful","“America the Beautiful”","America the Beautiful","अमेरिका द ब्यूटीफुल"),
       L("God Bless America","God Bless America","“God Bless America”","God Bless America","गॉड ब्लेस अमेरिका"),
       L("Yankee Doodle","Yankee Doodle","“Yankee Doodle”","Yankee Doodle","यांकी डूडल")],
    e:L("The national anthem is the Star-Spangled Banner.","El himno nacional es “The Star-Spangled Banner”.","Государственный гимн — “The Star-Spangled Banner”.","Milli marş “The Star-Spangled Banner”'dır.","राष्ट्रगान “द स्टार-स्पैंगल्ड बैनर” है।") },

  { cat:"sym", a:1,
    q:L("When do we celebrate Independence Day?","¿Cuándo celebramos el Día de la Independencia?","Когда отмечают День независимости?","Bağımsızlık Günü ne zaman kutlanır?","स्वतंत्रता दिवस कब मनाया जाता है?"),
    o:[L("January 1","1 de enero","1 января","1 Ocak","1 जनवरी"),
       L("July 4","4 de julio","4 июля","4 Temmuz","4 जुलाई"),
       L("November 11","11 de noviembre","11 ноября","11 Kasım","11 नवंबर"),
       L("December 25","25 de diciembre","25 декабря","25 Aralık","25 दिसंबर")],
    e:L("We celebrate Independence Day on July 4.","Celebramos el Día de la Independencia el 4 de julio.","День независимости отмечают 4 июля.","Bağımsızlık Günü 4 Temmuz'da kutlanır.","स्वतंत्रता दिवस 4 जुलाई को मनाया जाता है।") },

  { cat:"sym", a:2,
    q:L("Name one national U.S. holiday.","Nombra un día festivo nacional de EE. UU.","Назовите один государственный праздник США.","Bir ABD ulusal bayramı söyleyin.","अमेरिका का एक राष्ट्रीय अवकाश बताएं।"),
    o:[L("Cinco de Mayo","Cinco de Mayo","Cinco de Mayo","Cinco de Mayo","सिंको दे मायो"),
       L("Boxing Day","Boxing Day","День подарков","Boxing Day","बॉक्सिंग डे"),
       L("Thanksgiving","Día de Acción de Gracias","День благодарения","Şükran Günü","थैंक्सगिविंग"),
       L("Bastille Day","Día de la Bastilla","День взятия Бастилии","Bastille Günü","बैस्टिल दिवस")],
    e:L("National holidays include New Year's Day, Independence Day, Thanksgiving, Veterans Day, Memorial Day, Labor Day, and Christmas.","Festivos: Año Nuevo, Día de la Independencia, Acción de Gracias, Día de los Veteranos, etc.","Праздники: Новый год, День независимости, День благодарения, День ветеранов и др.","Bayramlar: Yılbaşı, Bağımsızlık Günü, Şükran Günü, Gaziler Günü vb.","अवकाश: नववर्ष, स्वतंत्रता दिवस, थैंक्सगिविंग, वेटरन्स डे आदि।") }
  ];

  // ---- categories (one base "Civics" practice + one Learn lesson over the same pool) ----
  var cats = [
    { id:"gov", kind:"core", icon:"🏛️",
      name:L("American Government","Gobierno estadounidense","Государство США","Amerikan Hükümeti","अमेरिकी सरकार"),
      blurb:L("Constitution, branches, Congress, rights & responsibilities.","Constitución, ramas, Congreso, derechos y responsabilidades.","Конституция, ветви власти, Конгресс, права и обязанности.","Anayasa, kollar, Kongre, haklar ve sorumluluklar.","संविधान, शाखाएँ, कांग्रेस, अधिकार और ज़िम्मेदारियाँ।") },
    { id:"hist", kind:"core", icon:"📜",
      name:L("American History","Historia estadounidense","История США","Amerikan Tarihi","अमेरिकी इतिहास"),
      blurb:L("Independence, the 1800s, recent history & important figures.","Independencia, siglo XIX, historia reciente y figuras importantes.","Независимость, XIX век, новейшая история и важные деятели.","Bağımsızlık, 1800'ler, yakın tarih ve önemli kişiler.","स्वतंत्रता, 1800 का दशक, हाल का इतिहास और महत्वपूर्ण हस्तियाँ।") },
    { id:"sym", kind:"core", icon:"🗽",
      name:L("Symbols & Holidays","Símbolos y festivos","Символы и праздники","Semboller ve Bayramlar","प्रतीक और अवकाश"),
      blurb:L("Geography, the flag, the anthem and national holidays.","Geografía, la bandera, el himno y los festivos nacionales.","География, флаг, гимн и государственные праздники.","Coğrafya, bayrak, marş ve ulusal bayramlar.","भूगोल, ध्वज, राष्ट्रगान और राष्ट्रीय अवकाश।") }
  ];

  // ---- UI strings (5 languages) ----
  var ui = {
    en:{ brand:"PassRoute", examName:"US Citizenship", tagline:"USCIS civics test — study in 5 languages",
      practice:"Practice Test", learn:"Learning Test", learnHint:"Study every question with the answer shown",
      heroTitle:"U.S. Citizenship — Civics Test", heroSub:"Practice the official USCIS civics questions. Choose a subject to begin.",
      start:"Start", question:"Question", correct:"Correct!", wrong:"Not quite", pick:"Pick an answer to continue", next:"Next",
      seeRes:"See results", quit:"Quit", back:"Back to subjects", results:"Results", score:"Score", passed:"Passed", failed:"Keep practicing",
      retry:"Try again", review:"Review", correctN:"correct", wrongN:"wrong", time:"Time", avg:"Avg/question",
      lesson:"Lesson", home:"Home", note:"Note: current office-holders (President, your Senators, Governor, capital) change over time and by state — the official test accepts current/your-state answers.",
      switchExam:"Switch exam", cdl:"Commercial (CDL)", dl:"Driver License (DL)", civ:"US Citizenship", src:"Answer" },
    es:{ brand:"PassRoute", examName:"Ciudadanía de EE. UU.", tagline:"Examen cívico de USCIS — estudia en 5 idiomas",
      practice:"Examen de práctica", learn:"Examen de aprendizaje", learnHint:"Estudia cada pregunta con la respuesta",
      heroTitle:"Ciudadanía de EE. UU. — Examen cívico", heroSub:"Practica las preguntas cívicas oficiales de USCIS. Elige un tema para empezar.",
      start:"Empezar", question:"Pregunta", correct:"¡Correcto!", wrong:"Casi", pick:"Elige una respuesta para continuar", next:"Siguiente",
      seeRes:"Ver resultados", quit:"Salir", back:"Volver a los temas", results:"Resultados", score:"Puntuación", passed:"Aprobado", failed:"Sigue practicando",
      retry:"Reintentar", review:"Repasar", correctN:"correctas", wrongN:"incorrectas", time:"Tiempo", avg:"Prom/pregunta",
      lesson:"Lección", home:"Inicio", note:"Nota: los funcionarios actuales (Presidente, sus senadores, gobernador, capital) cambian con el tiempo y por estado; el examen acepta las respuestas actuales/de su estado.",
      switchExam:"Cambiar examen", cdl:"Comercial (CDL)", dl:"Licencia de conducir (DL)", civ:"Ciudadanía", src:"Respuesta" },
    ru:{ brand:"PassRoute", examName:"Гражданство США", tagline:"Тест USCIS по обществознанию — на 5 языках",
      practice:"Практический тест", learn:"Обучающий тест", learnHint:"Изучайте каждый вопрос с ответом",
      heroTitle:"Гражданство США — тест по обществознанию", heroSub:"Тренируйтесь по официальным вопросам USCIS. Выберите тему, чтобы начать.",
      start:"Начать", question:"Вопрос", correct:"Верно!", wrong:"Почти", pick:"Выберите ответ, чтобы продолжить", next:"Далее",
      seeRes:"Результаты", quit:"Выйти", back:"К темам", results:"Результаты", score:"Счёт", passed:"Сдано", failed:"Продолжайте тренироваться",
      retry:"Ещё раз", review:"Разбор", correctN:"верно", wrongN:"неверно", time:"Время", avg:"Сред/вопрос",
      lesson:"Урок", home:"Главная", note:"Примечание: действующие лица (президент, ваши сенаторы, губернатор, столица) меняются со временем и по штату — на тесте принимаются текущие/местные ответы.",
      switchExam:"Сменить экзамен", cdl:"Коммерческие (CDL)", dl:"Водительские права (DL)", civ:"Гражданство", src:"Ответ" },
    tr:{ brand:"PassRoute", examName:"ABD Vatandaşlığı", tagline:"USCIS yurttaşlık sınavı — 5 dilde çalışın",
      practice:"Deneme Sınavı", learn:"Öğrenme Testi", learnHint:"Her soruyu cevabıyla birlikte çalışın",
      heroTitle:"ABD Vatandaşlığı — Yurttaşlık Sınavı", heroSub:"Resmi USCIS sorularını çalışın. Başlamak için bir konu seçin.",
      start:"Başla", question:"Soru", correct:"Doğru!", wrong:"Az kaldı", pick:"Devam etmek için bir cevap seçin", next:"Sonraki",
      seeRes:"Sonuçlar", quit:"Çık", back:"Konulara dön", results:"Sonuçlar", score:"Puan", passed:"Geçti", failed:"Çalışmaya devam",
      retry:"Tekrar dene", review:"İncele", correctN:"doğru", wrongN:"yanlış", time:"Süre", avg:"Ort/soru",
      lesson:"Ders", home:"Ana sayfa", note:"Not: güncel görevliler (Başkan, senatörleriniz, vali, başkent) zamanla ve eyalete göre değişir — sınav güncel/eyalet cevaplarını kabul eder.",
      switchExam:"Sınav değiştir", cdl:"Ticari (CDL)", dl:"Sürücü Belgesi (DL)", civ:"ABD Vatandaşlığı", src:"Cevap" },
    hi:{ brand:"PassRoute", examName:"अमेरिकी नागरिकता", tagline:"USCIS नागरिक शास्त्र परीक्षा — 5 भाषाओं में",
      practice:"अभ्यास परीक्षा", learn:"सीखने की परीक्षा", learnHint:"हर प्रश्न को उत्तर के साथ पढ़ें",
      heroTitle:"अमेरिकी नागरिकता — नागरिक शास्त्र परीक्षा", heroSub:"आधिकारिक USCIS प्रश्नों का अभ्यास करें। शुरू करने के लिए विषय चुनें।",
      start:"शुरू करें", question:"प्रश्न", correct:"सही!", wrong:"लगभग", pick:"जारी रखने के लिए उत्तर चुनें", next:"अगला",
      seeRes:"परिणाम देखें", quit:"छोड़ें", back:"विषयों पर वापस", results:"परिणाम", score:"स्कोर", passed:"उत्तीर्ण", failed:"अभ्यास जारी रखें",
      retry:"फिर प्रयास करें", review:"समीक्षा", correctN:"सही", wrongN:"गलत", time:"समय", avg:"औसत/प्रश्न",
      lesson:"पाठ", home:"होम", note:"नोट: वर्तमान पदाधिकारी (राष्ट्रपति, आपके सीनेटर, गवर्नर, राजधानी) समय और राज्य के अनुसार बदलते हैं — परीक्षा वर्तमान/आपके राज्य के उत्तर स्वीकार करती है।",
      switchExam:"परीक्षा बदलें", cdl:"वाणिज्यिक (CDL)", dl:"ड्राइवर लाइसेंस (DL)", civ:"अमेरिकी नागरिकता", src:"उत्तर" }
  };

  window.CIV = { ui:ui, cats:cats, q:Q };
})();
